### ISSUE TITLE
USER STORY: Account creation

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/events-in-town#1]
EPIC: <Account creation>

As a **User** I can **create an account** so that **i can contribute to the site**

**Acceptance Criteria**

- [x] User registration form with username and password
- [x] Create unique username and choose a password
- [x] User is created in Django admin panel

**Tasks**

- [x] Design and implement a registration form
- [x] Add validation and error handling
- [x] Test functionality
